'use client';

import { useEffect, useState } from 'react';
import { coupleData, type CoupleChapter, type MemoryPhoto } from '@/data/couple-data';
import { WaxSeal } from '@/components/wax-seal';

function Brand() { return <span className="brand"><strong>QUIROZ</strong><small>PAREJAS</small></span>; }

export default function Home() {
  const [stage, setStage] = useState<'cover' | 'letter' | 'index' | 'chapter' | 'final'>('cover');
  const [chapter, setChapter] = useState(0);
  const [lightbox, setLightbox] = useState<MemoryPhoto | null>(null);
  const chapters = coupleData.chapters.filter((item) => item.style !== 'letter');
  const current = chapters[chapter];
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') setLightbox(null); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  useEffect(() => { window.scrollTo({ top: 0, behavior: 'auto' }); }, [stage, chapter]);
  function openChapter(index: number) { setChapter(index); setStage(index === chapters.length - 1 ? 'final' : 'chapter'); }
  function next() { if (chapter >= chapters.length - 2) setStage('final'); else { setChapter(chapter + 1); setStage('chapter'); } }
  function previous() { if (chapter <= 0) setStage('index'); else { setChapter(chapter - 1); setStage('chapter'); } }

  if (stage === 'cover') return <main className="experience cover-screen"><img className="cover-reference" src="/assets/images/cover/quiroz-parejas-entry.jpeg" alt="" aria-hidden="true" /><button className="cover-open" onClick={() => setStage('letter')} aria-label="Abrir el regalo de aniversario">Abrir <span>→</span></button></main>;
  if (stage === 'letter') return <main className="experience letter-screen"><p className="letter-for">Para ti, Sofía</p><div className="letter-copy">{coupleData.letter.map((line) => <p key={line}>{line}</p>)}</div><p className="signature">Damián</p><button className="primary-button" onClick={() => setStage('index')}>Comenzar nuestra historia <span>→</span></button></main>;
  if (stage === 'index') return <main className="experience index-screen"><header><span className="catalog-mark">S&amp;D</span><nav aria-label="Secciones"><a href="#catalogo">Inicio</a><a href="#recuerdos">Recuerdos</a><a href="#favoritos">Favoritos</a></nav><button className="catalog-menu" aria-label="Abrir menú">•••</button></header><section className="catalog-hero" id="catalogo"><img src={chapters[0].images[0].src} alt="Sofía y Damián al comienzo de su historia" /><div className="catalog-hero__shade" /><div className="catalog-hero__content"><span className="catalog-kicker">Una historia original</span><h1>Sofía <i>&amp;</i> Damián</h1><p>En un año caben primeras conversaciones, viajes, días normales y una forma nueva de quererse.</p><div className="catalog-hero__meta"><span>09 recuerdos</span><span>2025 — 2026</span><span>Para siempre</span></div><div className="catalog-actions"><button className="catalog-play" onClick={() => openChapter(0)}>▶ <span>Continuar historia</span></button><button className="catalog-info" onClick={() => document.querySelector('#recuerdos')?.scrollIntoView({ behavior: 'smooth' })}>ⓘ <span>Ver recuerdos</span></button></div></div></section><section className="catalog-section" id="recuerdos"><div className="catalog-section__title"><h2>Mis recuerdos</h2><span>Desliza para explorar</span></div><nav className="catalog-row" aria-label="Índice de capítulos">{chapters.map((item, index) => <button className="catalog-card" key={item.number} onClick={() => openChapter(index)}><img src={item.images[0].src} alt={item.images[0].alt} /><span className="catalog-card__shade" /><span className="catalog-card__copy"><small>{item.number}</small><strong>{item.title}</strong></span></button>)}</nav></section><section className="catalog-section" id="favoritos"><div className="catalog-section__title"><h2>Momentos que guardo</h2><span>Una temporada de nosotros</span></div><nav className="catalog-row catalog-row--small" aria-label="Momentos destacados">{chapters.slice(4, 8).map((item, index) => <button className="catalog-card" key={`fav-${item.number}`} onClick={() => openChapter(index + 4)}><img src={item.images[0].src} alt={item.images[0].alt} /><span className="catalog-card__shade" /><span className="catalog-card__copy"><small>{item.number}</small><strong>{item.title}</strong></span></button>)}</nav></section></main>;
  const isFinal = stage === 'final';
  return <main className={`experience chapter-screen chapter-${current.style}`}>
    <header className="chapter-top"><button className="back-button" onClick={() => setStage('index')} aria-label="Volver al índice">← <span>Índice</span></button><span>{current.number} / {chapters.length}</span></header>
    {isFinal ? <section className="final-message"><div className="final-visual"><img src={current.images[0]?.src} alt={current.images[0]?.alt} /></div><div className="final-message__copy"><span className="chapter-label">09 — Cierre</span><h1>Un año de nosotros.</h1>{current.body.slice(1).map((line) => <p key={line}>{line}</p>)}<div className="final-cta"><strong>Sofía &amp; Damián</strong><button className="primary-button" onClick={() => setStage('index')}>Volver a nuestros recuerdos</button></div></div></section> : <section className="chapter-layout" key={current.number}><div className="chapter-visual">{current.images.map((image) => <button className="memory-photo" key={image.src} onClick={() => setLightbox(image)} aria-label={`Ampliar ${image.alt}`}><img src={image.src} alt={image.alt} style={{ objectPosition: image.position }} /></button>)}</div><article className="chapter-copy"><span className="chapter-label">Capítulo {current.number}</span><h1>{current.title}</h1><div className="body-copy">{current.body.map((line) => <p key={line}>{line}</p>)}</div></article></section>}
    <nav className="chapter-nav" aria-label="Navegación de recuerdos"><button onClick={previous}>← Anterior</button>{!isFinal && <button onClick={() => setStage('index')}>Índice</button>}{!isFinal && <button onClick={next}>Siguiente recuerdo →</button>}</nav>
    {lightbox && <div className="lightbox" role="dialog" aria-modal="true" aria-label="Fotografía ampliada" onClick={() => setLightbox(null)}><button className="lightbox-close" onClick={() => setLightbox(null)} aria-label="Cerrar fotografía">×</button><img src={lightbox.src} alt={lightbox.alt} onClick={(event) => event.stopPropagation()} /></div>}
  </main>;
}
